server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/Navarasan08/cloud-config-server.git"
          clone-on-start: true
          default-label: main
          search-paths:
            - .  # Adjust if your configs are inside a folder (e.g., "config-files")
  profiles:
    active: native  # or omit this if you're using git only

management:
  endpoints:
    web:
      exposure:
        include: "*"
